### PR TITLE
fixed excellon-drill snapshot test

### PR DESCRIPTION
**Pull request by ShiboSoftwareDev**
file now diffs and doesn't concatenate like it used to

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
it's weird that the string was the issue- is there an underlying issue in bun-match-svg?

**Comment by ShiboSoftwareDev** [comment]
I just read an example in their docs and it didn't use a string

**Comment by ShiboSoftwareDev** [comment]
@seveibar these are the props and you passed a string as the first argument
image
not sure what you intended

**Comment by seveibar** [comment]
oh it's `toMatchSnapshot` not `toMatchSvgSnapshot`

**Pull request merged**
